# Generated by Django 5.0.6 on 2024-06-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brickyard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("ruc", models.CharField(blank=True, max_length=11)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ladrillera",
            },
        ),
        migrations.CreateModel(
            name="EmissionLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, max_length=250)),
                ("email_alert", models.BooleanField(default=False)),
                ("app_alert", models.BooleanField(default=False)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "limite_emision",
            },
        ),
        migrations.CreateModel(
            name="GasType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tipo_gas",
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("address", models.CharField(blank=True, max_length=200)),
                ("phone", models.IntegerField(blank=True, null=True)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "institucion",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "estado_medicion",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("status", models.BooleanField(default=False)),
                (
                    "battery_level",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brickyard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.brickyard"
                    ),
                ),
            ],
            options={
                "db_table": "dispositivo",
            },
        ),
        migrations.CreateModel(
            name="LimitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("is_modified", models.BooleanField(default=False)),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "emission_limit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.emissionlimit",
                    ),
                ),
                (
                    "gas_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.gastype"
                    ),
                ),
            ],
            options={
                "db_table": "historial_limite",
            },
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brickyard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.brickyard"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.institution",
                    ),
                ),
            ],
            options={
                "db_table": "administracion",
            },
        ),
        migrations.AddField(
            model_name="emissionlimit",
            name="management",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.management"
            ),
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "gas_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.gastype"
                    ),
                ),
            ],
            options={
                "db_table": "medicion",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_read", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "limit_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.limithistory",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.measurement",
                    ),
                ),
            ],
            options={
                "db_table": "alerta",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.device"),
                ),
                (
                    "gas_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.gastype"
                    ),
                ),
            ],
            options={
                "db_table": "sensor",
            },
        ),
        migrations.AddField(
            model_name="measurement",
            name="sensor",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.sensor"),
        ),
    ]
