# Generated by Django 5.0.7 on 2024-08-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0002_remove_management_created_at_and_more_squashed_0016_alter_alert_options_remove_alert_limit_history_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionlimit",
            name="is_public",
            field=models.BooleanField(
                default=False, help_text="Este límite de emisión es público", verbose_name="Público"
            ),
        ),
    ]
