# Generated by Django 5.0.7 on 2024-08-09 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_emissionlimit_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alert",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
            },
        ),
        migrations.RemoveField(
            model_name="alert",
            name="date",
        ),
        migrations.AddField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Última actualización"),
        ),
    ]
