# Generated by Django 5.0.7 on 2024-08-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_alert_options_remove_alert_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alert",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="alert",
            name="short_description",
            field=models.TextField(blank=True, max_length=300, verbose_name="Descripción corta"),
        ),
        migrations.AlterField(
            model_name="emissionlimit",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Este límite de emisión puede ser visto por las ladrilleras",
                verbose_name="Público",
            ),
        ),
    ]
