# Generated by Django 5.0.7 on 2024-08-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_rename_last_update_alert_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brickyard",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="device",
            old_name="last_update",
            new_name="updated_at",
        ),
    ]
