# Generated by Django 5.0.7 on 2024-08-11 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_rename_last_update_brickyard_updated_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emissionlimit",
            old_name="last_update",
            new_name="updated_at",
        ),
        migrations.AddField(
            model_name="emissionlimit",
            name="brickyard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.brickyard",
                verbose_name="Ladrillera",
            ),
        ),
    ]
