# Generated by Django 5.0.7 on 2024-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_last_update_gastype_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emissionlimit",
            name="is_default",
        ),
        migrations.AddField(
            model_name="emissionlimit",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Activo"),
        ),
    ]
