# Generated by Django 5.0.7 on 2024-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_brickyard_address_alter_brickyard_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(max_length=200, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
    ]
