# Generated by Django 5.0.7 on 2024-09-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_institution_address_alter_institution_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
    ]
