# Generated by Django 5.0.8 on 2024-10-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_remove_device_battery_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="emissionlimit",
            name="gap_time",
            field=models.IntegerField(
                default=0,
                help_text="Tiempo en segundos que debe pasar para que se envíe una nueva alertas. Por defecto: 0",
                verbose_name="Tiempo entre alertas (segundos)",
            ),
        ),
    ]
