# Generated by Django 5.0.8 on 2024-10-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_emissionlimit_gap_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="brickyard",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="Ladrillera es visible"),
        ),
    ]
