# Generated by Django 5.0.8 on 2024-10-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_brickyard_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brickyard",
            name="visible",
            field=models.BooleanField(
                default=True, help_text="Visible para los usuarios", verbose_name="Visible"
            ),
        ),
    ]
