# Generated by Django 5.0.6 on 2024-06-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='management',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='management',
            name='last_update',
        ),
        migrations.AddField(
            model_name='institution',
            name='brickyards',
            field=models.ManyToManyField(through='api.Management', to='api.brickyard', verbose_name='Ladrilleras'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Leído'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='limit_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.limithistory', verbose_name='Historial de límites'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='measurement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.measurement', verbose_name='Medición'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='brickyard',
            name='ruc',
            field=models.CharField(blank=True, max_length=11, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Nivel de batería'),
        ),
        migrations.AlterField(
            model_name='device',
            name='brickyard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brickyard', verbose_name='Ladrillera'),
        ),
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='app_alert',
            field=models.BooleanField(default=False, verbose_name='Alerta de aplicación'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='description',
            field=models.TextField(blank=True, max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='email_alert',
            field=models.BooleanField(default=False, verbose_name='Alerta de correo electrónico'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='management',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.management', verbose_name='Administración'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='gastype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='gastype',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='gastype',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='emission_limit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.emissionlimit', verbose_name='Límite de emisión'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='gas_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gastype', verbose_name='Tipo de gas'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='is_modified',
            field=models.BooleanField(default=False, verbose_name='Es modificable'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='max_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Límite máximo'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='management',
            name='brickyard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.brickyard', verbose_name='Ladrillera'),
        ),
        migrations.AlterField(
            model_name='management',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='gas_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor', verbose_name='Sensor'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
