# Generated by Django 5.0.6 on 2024-06-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_management_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brickyard',
            options={'verbose_name': 'Ladrillera', 'verbose_name_plural': 'Ladrilleras'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Institución', 'verbose_name_plural': 'Instituciones'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Administración', 'verbose_name_plural': 'Administraciones'},
        ),
        migrations.AlterUniqueTogether(
            name='management',
            unique_together={('brickyard', 'institution')},
        ),
    ]
