# Generated by Django 5.0.6 on 2024-06-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_brickyard_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Dispositivo', 'verbose_name_plural': 'Dispositivos'},
        ),
        migrations.AlterField(
            model_name='device',
            name='battery_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Nivel de batería'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Está activado'),
        ),
    ]
