# Generated by Django 5.0.6 on 2024-06-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_device_options_alter_device_battery_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
