# Generated by Django 5.0.6 on 2024-06-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_gastype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gastype',
            options={'verbose_name': 'Tipo de gas', 'verbose_name_plural': 'Tipos de gas'},
        ),
        migrations.AddField(
            model_name='gastype',
            name='abbreviation',
            field=models.CharField(default=1, max_length=10, verbose_name='Abreviatura'),
            preserve_default=False,
        ),
    ]
