# Generated by Django 5.0.6 on 2024-06-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sensor_options_remove_measurement_gas_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='status_measurement',
            new_name='status',
        ),
    ]
