# Generated by Django 5.0.6 on 2024-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_status_measurement_measurement_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Medición', 'verbose_name_plural': 'Mediciones'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Estado de la medición', 'verbose_name_plural': 'Estados de la medición'},
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Medido en mg x m3', max_digits=6, verbose_name='Valor'),
        ),
    ]
