# Generated by Django 5.0.6 on 2024-06-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_measurement_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionlimit',
            options={'verbose_name': 'Límite de emisión', 'verbose_name_plural': 'Límites de emisión'},
        ),
        migrations.AlterModelOptions(
            name='limithistory',
            options={'verbose_name': 'Historial de límite', 'verbose_name_plural': 'Historial de límites'},
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='app_alert',
            field=models.BooleanField(default=False, help_text='Se enviará una notificación a la aplicación', verbose_name='Alerta por aplicación'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='email_alert',
            field=models.BooleanField(default=False, help_text='Se enviará una notificación por correo electrónico', verbose_name='Alerta por correo electrónico'),
        ),
        migrations.AlterField(
            model_name='limithistory',
            name='max_limit',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Límite máximo permitido en mg x m3', max_digits=7, verbose_name='Límite máximo'),
        ),
    ]
