# Generated by Django 5.0.6 on 2024-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_emissionlimit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=5, default=0, help_text='Medido en mg x m3', max_digits=9, verbose_name='Valor'),
        ),
    ]
