# Generated by Django 5.0.6 on 2024-06-17 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_measurement_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionlimit',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.institution', verbose_name='Institución'),
        ),
        migrations.AlterField(
            model_name='emissionlimit',
            name='management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.management', verbose_name='Administración'),
        ),
    ]
