# Generated by Django 5.0.6 on 2024-06-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_emissionlimit_institution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionlimit',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Este límite de emisión es el predeterminado', verbose_name='Predeterminado'),
        ),
    ]
