# Generated by Django 5.0.6 on 2024-06-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_emissionlimit_is_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['date'], name='medicion_date_54165f_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['sensor'], name='medicion_sensor__e8d3ee_idx'),
        ),
    ]
